### PR TITLE
Fix for #5

### PR DESCRIPTION
**Pull request by bjarnef**
Renamed tag-label to "tag-label-blue" and included a "tag-label-red" as
well.  Changed tree icon to the "red icon", when discount not is active.
I included the new image icon in the embeded resource.

I have only a check on the active property. I'm not sure if the active
property change when the discount code expire, otherwise there could
also be a check on the startdate and enddate, so the blue tag icon is
displayed when the discount is active in the webshop and the red icon,
when it isn't active.

### CODE REVIEW

**Comment by andersburla** [comment]
Please let the "tab-label-blue" still be "tag-label" as that is the name of the icon from Fugue icon package.

If you could make the icon change based on the start and end date that would be great. The active bool is only for the check mark that indicates if a campaign should be active.

**Comment by andersburla** [comment]
Hi Bjarne
Please make this pull request to the dev branch instead of the master. Master branch is used for releases only.

**Comment by bjarnef** [comment]
Okay, I didn't notice the dev branch before I had submitted the pull requests. Should I create a new pull  request or commit for this?

But when the active bool isn't checked the campaign isn't active - then why not mark it with a red label icon? My thought was to use a red icon when the campaign isn't valid in the store and a blue icon when the campaign is valid. So in my opinion it doesn't matter whether the date range doesn't match or the shop owner choose to disable the campaign.

**Comment by andersburla** [comment]
Yes you should create a new pull request :)

Yes the campaign is inactive when the checkbox isnt checked. I think the red icon should reflect both the active status of the campaign and if its "active" because of the start and end date

**Pull request closed without merging**
